<!-- Page d'ajout d'un article -->
<h2><i class="fa fa-pencil"></i> Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="add_post.php" method="POST">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15"></textarea>
            </li>
            <li>
                <!-- Récupération du nom de l'auteur -->
                <label for="author">Auteur :</label>
                
               
                <select id="author" name="author">
                         
                        <option value="<?= $_GET['AuthorId'] ?>">Jonh Wick</option>
                     
                </select>
                
            </li>
            <li>
                <!-- Récupération des noms des catégories -->
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                    <?php foreach($Category as $Category): ?>
                        <option value="<?= $Category['id'] ?>"><?= $Category['Name'] ?></option>
                       <?php endforeach; ?>
                </select>
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>