<!-- Page d'accueil -->
<h2><i class="fa fa-home"></i> Accueil</h2>

<!-- Liste des articles du blog -->
<ul class="post-list">
    <?php foreach ($messages as $message) :?>
        <li class="post">
            <h3>
                <i class="fa fa-hand-o-right"></i>&nbsp;
                <!-- Lien vers article de blog détaillé avec les commentaires -->
                <?= $message['Title'] ?>
                <a href="" title="Consulter l'article">
                    
                <!-- Titre du post ici -->
                </a>
            </h3>
            <!-- Seul un extrait de l'article du blog est affiché -->
            <article><?= $message['Contents'] ?></article>
            <small>
                Rédigé par 
                le <?= $message['TimeStamp'] ?>
            </small>
           
        </li>
     <?php endforeach; ?>
</ul>